quarkus.http.port=9695
quarkus.application.name=purchasing-demo

# ---------------------------------------------------------
# PostgreSQL
# ---------------------------------------------------------

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=purchasing
quarkus.datasource.password=purchasing
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/purchasing

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

quarkus.devservices.enabled=false

# Demo only.
# Use Flyway migrations instead in production.
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# ---------------------------------------------------------
# Quarkus Flow
# ---------------------------------------------------------

# Persist Flow state using JPA.
#quarkus.flow.persistence.enabled=false

# ---------------------------------------------------------
# Flow HTTP
# ---------------------------------------------------------

#quarkus.flow.http.client.connect-timeout=5000
#quarkus.flow.http.client.read-timeout=10000

# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------

quarkus.log.category."io.quarkiverse.flow".level=INFO

# Kafka broker
kafka.bootstrap.servers=localhost:9092

quarkus.flow.messaging.devservices-messaging-enabled=true

